<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Article;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function addDisabled(
        string $title,
        string $text,
        string $tags,
        string $url
    ): Article {
        $date = new \DateTimeImmutable('now');
        $enabled = false;
        $article = new Article($title, $text, $date, $tags, $url, $enabled);
        $this->_em->persist($article);
        return $article;
    }
}
